apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdemo
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 40
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: chauhanhimani/todo-app:build-25
        ports:
        - containerPort: 80
